local map = vim.keymap.set

-- Better escape
map("i", "jk", "<Esc>", { desc = "Exit insert mode" })
map("i", "jj", "<Esc>", { desc = "Exit insert mode" })

-- Save
map({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save file" })

-- Quit
map("n", "<leader>qq", "<cmd>qa<cr>", { desc = "Quit all" })

-- Better up/down (handle wrapped lines)
map({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
map({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })

-- Window resize
map("n", "<C-Up>", "<cmd>resize +10<cr>", { desc = "Increase window height" })
map("n", "<C-Down>", "<cmd>resize -10<cr>", { desc = "Decrease window height" })
map("n", "<C-Right>", "<cmd>vertical resize +10<cr>", { desc = "Increase window width" })
map("n", "<C-Left>", "<cmd>vertical resize -10<cr>", { desc = "Decrease window width" })

-- Window splits
map("n", "<leader>wj", "<C-W>s", { desc = "Split window below" })
map("n", "<leader>wl", "<C-W>v", { desc = "Split window right" })
map("n", "<leader>wd", "<C-w>c", { desc = "Delete window" })

-- Buffer navigation
map("n", "H", "<cmd>bprevious<cr>", { desc = "Previous buffer" })
map("n", "L", "<cmd>bnext<cr>", { desc = "Next buffer" })
map("n", "<leader>bb", "<cmd>e #<cr>", { desc = "Switch to other buffer" })

-- Move lines
map("n", "<A-Down>", "<cmd>m .+1<cr>==", { desc = "Move line down" })
map("n", "<A-Up>", "<cmd>m .-2<cr>==", { desc = "Move line up" })
map("i", "<A-Down>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move line down" })
map("i", "<A-Up>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move line up" })
map("v", "<A-Down>", ":m '>+1<cr>gv=gv", { desc = "Move selection down" })
map("v", "<A-Up>", ":m '<-2<cr>gv=gv", { desc = "Move selection up" })

-- Better indenting (stay in visual mode)
map("v", "<", "<gv")
map("v", ">", ">gv")

-- Better paste (don't overwrite register)
map("v", "p", '"_dP', { desc = "Paste without overwriting" })

-- Don't yank on delete char
map({ "n", "v" }, "x", '"_x')
map({ "n", "v" }, "X", '"_X')

-- Copy whole file to clipboard
map("n", "<C-c>", ":%y+<cr>", { desc = "Copy whole file" })

-- Clear search highlight
map({ "i", "n" }, "<esc>", "<cmd>noh<cr><esc>", { desc = "Clear search highlight" })

-- Center screen after scrolling
map("n", "<C-d>", "<C-d>zz", { desc = "Scroll down centered" })
map("n", "<C-u>", "<C-u>zz", { desc = "Scroll up centered" })
map("n", "n", "nzzzv", { desc = "Next search centered" })
map("n", "N", "Nzzzv", { desc = "Previous search centered" })

-- Undo/Redo
map("n", "U", "<C-r>", { desc = "Redo" })

-- Diagnostic navigation
map("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
map("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
map("n", "<leader>l", vim.diagnostic.open_float, { desc = "Line diagnostics" })
map("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Diagnostics to loclist" })

-- Toggle inlay hints
map("n", "<leader>ht", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, { desc = "Toggle inlay hints" })

-- Smart K - hover if LSP supports it, otherwise show man/help
map("n", "K", function()
  -- Check if any client supports hover
  local clients = vim.lsp.get_clients({ bufnr = 0 })
  local hover_client = nil
  for _, client in ipairs(clients) do
    if client.supports_method("textDocument/hover") then
      hover_client = client
      break
    end
  end

  if hover_client then
    -- Call hover only on the client that supports it
    vim.lsp.buf.hover()
  elseif vim.bo.filetype == "vim" or vim.bo.filetype == "help" then
    vim.cmd("h " .. vim.fn.expand("<cword>"))
  elseif vim.bo.filetype == "man" then
    vim.cmd("Man " .. vim.fn.expand("<cword>"))
  elseif #clients > 0 then
    -- LSP attached but no hover support (e.g., ESLint only - ts_ls may still be loading)
    local client_names = {}
    for _, c in ipairs(clients) do
      table.insert(client_names, c.name)
    end
    vim.notify("Attached: " .. table.concat(client_names, ", ") .. " (no hover support yet)", vim.log.levels.INFO)
  else
    vim.notify("No LSP available for this buffer", vim.log.levels.INFO)
  end
end, { desc = "Hover (LSP/help/man)" })

-- CLAUDE.md
map("n", "<leader>Cg", function()
  vim.cmd("edit " .. vim.fn.expand("~/.dotfiles/.claude/CLAUDE.global.md")) -- source; ~/.claude/CLAUDE.md is generated by sync-llm
end, { desc = "Open global CLAUDE.md" })

map("n", "<leader>Cp", function()
  local root = vim.fs.root(0, ".git") or vim.uv.cwd()
  local path = root .. "/.claude/CLAUDE.md"
  local dir = root .. "/.claude"
  if vim.fn.isdirectory(dir) == 0 then
    vim.fn.mkdir(dir, "p")
  end
  vim.cmd("edit " .. path)
end, { desc = "Open project CLAUDE.md" })
